### ISSUE TITLE
crates.io outdated version

### ISSUE THREAD

**Issue by bernardoaraujor** [natemara/bmp280#1]
https://crates.io/crates/bmp280 resolves to `0.2.1`.
I'd like to be able to use `cargo` and resolve to `0.3.0`.

**Comment by lily-mara** [comment]
Hi @bernardoaraujor I'm very sorry that I let this sit idle for so long. I have published 0.3.0 to crates.io, and I will merge in #2 very soon and will publish those changes at that time also.
